media/videos/Combinatorial/1080p60/full_permutation.mp4: Combinatorial.py
	manimce -qh $<
media/videos/knapsack01/1080p60/knapsack01.mp4: knapsack01.py
	manimce -qh $<
media/videos/knapsack01_1d/1080p60/knapsack01_1d.mp4: knapsack01_1d.py
	manimce -qh $<